version: "3.8"

services:
  uniapi:
    image: yym68686/uni-api:latest
    restart: unless-stopped
    volumes:
      - /home/ubuntu/uniapi/api.yaml:/home/api.yaml
      - /home/ubuntu/uniapi/data:/home/data

  uniapi-frontend:
    image: ghcr.io/melosbot/uni-api-status:latest
    restart: unless-stopped
    ports:
      - "9090:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_YAML_PATH=/app/config/api.yaml
      - STATS_DB_PATH=/app/data/stats.db
    volumes:
      - /home/ubuntu/uniapi/api.yaml:/app/config/api.yaml
      - /home/ubuntu/uniapi/data:/app/data:ro
